### ISSUE TITLE
Unicode chars in --author-name not handled properly

### ISSUE THREAD

**Issue by DataStudioRisques** [arkinmodi/add-license-header#31]
Here's our pre-commit config file : 

```
  - repo: https://github.com/arkinmodi/add-license-header
    rev: v2.3.1
    hooks:
    - id: add-license-header
      types: [python]
      args:
          - --author-name
          - Covféfé
          - --license
          - |
            Copyright $create_year $author_name
```

Which results in this : 

```
# Copyright 2025 covf�f�
```
