### ISSUE TITLE
Reading from pyproject.toml

### ISSUE THREAD

**Issue by natibek** [arkinmodi/add-license-header#34]
In the project I used this for, I used `pyproject.toml` file, which is already used to configure other formatting tools to configure the license, create-year, and author-name instead of having to pass them as command line arguments directly. I had a field like below in the file and read that to configure the arguments that are used to run `add-license-header`.
```toml
[tool.add-license-header]
license = "..."
create_year = ""
author_name = ""
```
 Is that a feature that you think is worth adding?
